package com.hedan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLACK_NUMBER".
 */
public class BlackNumber {

    private Long id;
    /** Not-null value. */
    private String phone;
    /** Not-null value. */
    private java.util.Date ctime;

    public BlackNumber() {
    }

    public BlackNumber(Long id) {
        this.id = id;
    }

    public BlackNumber(Long id, String phone, java.util.Date ctime) {
        this.id = id;
        this.phone = phone;
        this.ctime = ctime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public java.util.Date getCtime() {
        return ctime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCtime(java.util.Date ctime) {
        this.ctime = ctime;
    }

}
