package com.hedan.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLACK_NUMBER".
 */
public class BlackNumber {

    private Long id;
    /** Not-null value. */
    private String phone;
    /** Not-null value. */
    private String name;
    private Boolean call_intercept;
    private Boolean sms_intercept;
    /** Not-null value. */
    private java.util.Date ctime;

    public BlackNumber() {
    }

    public BlackNumber(Long id) {
        this.id = id;
    }

    public BlackNumber(Long id, String phone, String name, Boolean call_intercept, Boolean sms_intercept, java.util.Date ctime) {
        this.id = id;
        this.phone = phone;
        this.name = name;
        this.call_intercept = call_intercept;
        this.sms_intercept = sms_intercept;
        this.ctime = ctime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    public Boolean getCall_intercept() {
        return call_intercept;
    }

    public void setCall_intercept(Boolean call_intercept) {
        this.call_intercept = call_intercept;
    }

    public Boolean getSms_intercept() {
        return sms_intercept;
    }

    public void setSms_intercept(Boolean sms_intercept) {
        this.sms_intercept = sms_intercept;
    }

    /** Not-null value. */
    public java.util.Date getCtime() {
        return ctime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCtime(java.util.Date ctime) {
        this.ctime = ctime;
    }

}
