package com.hedan.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.hedan.dao.Note;
import com.hedan.dao.Customer;
import com.hedan.dao.order;
import com.hedan.dao.BlackNumber;

import com.hedan.dao.NoteDao;
import com.hedan.dao.CustomerDao;
import com.hedan.dao.orderDao;
import com.hedan.dao.BlackNumberDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig noteDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig blackNumberDaoConfig;

    private final NoteDao noteDao;
    private final CustomerDao customerDao;
    private final orderDao orderDao;
    private final BlackNumberDao blackNumberDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        noteDaoConfig = daoConfigMap.get(NoteDao.class).clone();
        noteDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(orderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        blackNumberDaoConfig = daoConfigMap.get(BlackNumberDao.class).clone();
        blackNumberDaoConfig.initIdentityScope(type);

        noteDao = new NoteDao(noteDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new orderDao(orderDaoConfig, this);
        blackNumberDao = new BlackNumberDao(blackNumberDaoConfig, this);

        registerDao(Note.class, noteDao);
        registerDao(Customer.class, customerDao);
        registerDao(order.class, orderDao);
        registerDao(BlackNumber.class, blackNumberDao);
    }
    
    public void clear() {
        noteDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        blackNumberDaoConfig.getIdentityScope().clear();
    }

    public NoteDao getNoteDao() {
        return noteDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public orderDao getOrderDao() {
        return orderDao;
    }

    public BlackNumberDao getBlackNumberDao() {
        return blackNumberDao;
    }

}
